A couple of fixes to memento-nginx after inital live test

diff --git a/debian/memento-nginx.prerm b/debian/memento-nginx.prerm
--- a/debian/memento-nginx.prerm
+++ b/debian/memento-nginx.prerm
@@ -1,9 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 
-# @file create-memento-nginx-config
+# @file clearwater-nginx.prerm
 #
 # Project Clearwater - IMS in the Cloud
-# Copyright (C) 2014 Metaswitch Networks Ltd
+# Copyright (C) 2013  Metaswitch Networks Ltd
 #
 # This program is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -34,46 +34,45 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
-# This file creates an nginx config file for Memento.
+#
+# see: dh_installdeb(1)
 
-. /etc/clearwater/config
+set -e
 
-if [ -z $memento_hostname ]
-then
-  memento_hostname="memento.$home_domain"
-fi
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-# Create the config file, using the memento_hostname we've got from
-# /etc/clearwater/config
-cat > /etc/nginx/sites-available/memento << EOF
-server {
-        listen       443;
-        server_name  $memento_hostname;
+NAME=clearwater-nginx
 
-        ssl                  on;
-        ssl_certificate /etc/nginx/ssl/nginx.crt;
-        ssl_certificate_key /etc/nginx/ssl/nginx.key;
+#
+# These functions undo their counterparts in clearwater-nginx.postinst
+#
 
-        ssl_session_timeout  5m;
+case "$1" in
+    remove|upgrade|deconfigure)
+        nginx_dissite memento && service nginx reload
+    ;;
 
-        ssl_protocols  SSLv2 SSLv3 TLSv1;
-        ssl_ciphers  ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP;
-        ssl_prefer_server_ciphers   on;
+    upgrade|failed-upgrade)
+    ;;
 
-        location /ping {
-                proxy_pass http://localhost:11888;
-        }
-        location /org.projectclearwater.call-list {
-                proxy_pass http://localhost:11888;
-        }
-}
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
 
-server {
-        listen      80;
-        server_name $memento_hostname;
-        return 301 https://$host$request_uri;
-}
-EOF
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
-# Enable the new Memento site
-nginx_ensite memento
+#DEBHELPER#
+
+exit 0
