Poll memento via nginx using HTTPS

diff --git a/memento-nginx.root/usr/share/clearwater/bin/poll_memento_https b/memento-nginx.root/usr/share/clearwater/bin/poll_memento_https
--- a/memento-nginx.root/usr/share/clearwater/bin/poll_memento_https
+++ b/memento-nginx.root/usr/share/clearwater/bin/poll_memento_https
@@ -1,9 +1,9 @@
-#!/bin/sh
+#!/bin/bash
 
-# @file memento-nginx.monit
+# @file poll_memento_https.sh
 #
 # Project Clearwater - IMS in the Cloud
-# Copyright (C) 2013  Metaswitch Networks Ltd
+# Copyright (C) 2014  Metaswitch Networks Ltd
 #
 # This program is free software: you can redistribute it and/or modify it
 # under the terms of the GNU General Public License as published by the
@@ -34,6 +34,13 @@
 # under which the OpenSSL Project distributes the OpenSSL toolkit software,
 # as those licenses appear in the file LICENSE-OPENSSL.
 
+# This script checks that port 11888 is open to poll memento and check whether it
+# is healthy.
+
+# In case memento has only just restarted, give it a few seconds to come up
+sleep 5
+
+# Read the config, defaulting appropriately.
 . /etc/clearwater/config
 
 if [ -z $memento_hostname ]
@@ -41,40 +48,16 @@ then
   memento_hostname="memento.$home_domain"
 fi
 
-# Set up the monit configuration for memento with the right IP addresses and ports
-cat > /etc/monit/conf.d/memento-nginx.monit <<EOF
-# Check the server's public interfaces.  We put this first so that we process
-# failed polls (and maybe kill the server) before we process the restart.
+# Send HTTP request and check that the response is "OK".
+curl -f -g -m 2 -s -H 'Host: $memento_hostname' https://127.0.0.1/ping 2> /tmp/poll-memento-https.sh.stderr.$$ | tee /tmp/poll-memento-https.sh.stdout.$$ | head -1 | egrep -q "^OK$"
+rc=$?
 
-check process nginx pidfile /var/run/nginx.pid
-  start program   = "/bin/bash -c '/usr/share/clearwater/bin/issue_alarm.py monit 5001.3; /etc/init.d/nginx start'"
-  stop program    = "/bin/bash -c '/usr/share/clearwater/bin/issue_alarm.py monit 5001.3; /etc/init.d/nginx stop'"
-  restart program = "/bin/bash -c '/usr/share/clearwater/bin/issue_alarm.py monit 5001.3; /etc/init.d/nginx abort-restart'"
+# Check the return code and log if appropriate.
+if [ $rc != 0 ] ; then
+  echo HTTPS failed to https://127.0.0.1/ping >&2
+  cat /tmp/poll-memento-https.sh.stderr.$$ >&2
+  cat /tmp/poll-memento-https.sh.stdout.$$ >&2
+fi
+rm -f /tmp/poll-memento-https.sh.stderr.$$ /tmp/poll-memento-https.sh.stdout.$$
 
-  if memory is greater than 80% for 3 cycles
-     then restart
-
-  if uptime < 30 seconds
-     then exec "/bin/true"
-     else if succeeded
-         then exec "/usr/share/clearwater/bin/issue_alarm.py monit 5001.1"
-
-  if failed host 127.0.0.1 port 80 protocol http
-     hostheader 'localhost'
-     request "/ping"
-     timeout 1 second
-     for 3 cycles
-     then restart
-
-check program poll_memento_https with path "/usr/share/clearwater/bin/poll_memento_https.sh"
-
-  if status != 0 for 2 cycles
-    then exec "/usr/share/clearwater/bin/issue_alarm.py monit 5007.3"
-    else if succeeded
-        then exec "/usr/share/clearwater/bin/issue_alarm.py monit 5007.1"
-
-EOF
-chmod 0644 /etc/monit/conf.d/memento.monit
-
-# Force monit to reload its configuration
-reload clearwater-monit || true
+exit $rc
